[language-server]
html-templ= { command = "lsportal-go",
 args = 
['--exclusion',
 '({{[\s\S]*?}})',
    'html','htmlT[\n\s]*?\([\n\s]*?`([\s\S]*?)`[\s\n\,]*?\)',"vscode-html-language-server","--","--stdio"], config = {  hostInfo="helix" } }

[[language]]
name = "go"
language-servers = ["gopls","html-templ","tailwindcss-ls"  ]

[language-server.tailwindcss-ls]
config = { userLanguages = { go= "html", "*.go" = "html" } }
